dist: trusty

sudo: false

language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- 7.4
- nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  yarn: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

install:
  # Update Composer itself to the latest version (https://getcomposer.org/doc/03-cli.md#self-update-selfupdate-).
  - composer self-update
  # Install Composer packages.
  - composer install

script:
  - composer phpcs
